name: my-app

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    environment: 
      MONGO_URL: ${MONGO_URL}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-app-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - mongo
      - redis
    networks:
      - my-app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - my-app-network

volumes:
  mongo_data:
  redis_data:

networks:
  my-app-network: {}
